
/* lineofbusiness  seeding */
insert into lineofbusiness(name)
values
    ('Ingénierie logicielle'),
    ('Stratégie et performance d''affaires'),
    ('Agilité et changement des organisations'),
    ('Direction de projets et de programmes'),
    ('Ingénierie des solutions, des processus et des systèmes'),
    ('Infonuagique et infrastructure'),
    ('Cybersécurité et risques d''entreprise'),
    ('Progiciel de gestion'),
    ('Données massives, intelligence artificielle et d''affaires');

insert into recruiter (name, email)
values
        ('Issy Gaymar', 'igaymar0@google.com.hk'),
        ('Winnie Lindeman', 'wlindeman1@rediff.com'),
        ('Estrellita Dauney', 'edauney2@about.com'),
        ('Derby Goodwin', 'dgoodwin3@pbs.org'),
        ('Davidde Kirsz', 'dkirsz4@ustream.tv'),
        ('Lory Yitzhok', 'lyitzhok0@cargocollective.com'),
        ('Ralph Francescoccio', 'rfrancescoccio1@mtv.com'),
         ('Yasmin Conklin', 'yconklin2@state.gov'),
        ('Manda Mayze', 'mmayze3@hibu.com'),
         ('Barthel Naughton', 'bnaughton4@cdc.gov'),
         ('Kincaid Jouannisson', 'kjouannissona@gizmodo.com'),
         ('Levey Harnell', 'lharnellb@netvibes.com'),
         ('Algernon Jevon', 'ajevonc@mit.edu'),
         ('Northrop Osment', 'nosmentd@mysql.com'),
         ('Gibb Shedden', 'gsheddene@cafepress.com'),
         ('Deck Mityukov', 'dmityukovf@hostgator.com'),
         ('Lizette Wolfenden', 'lwolfendeng@sbwire.com'),
         ('Holmes O''Kynsillaghe', 'hokynsillagheh@irs.gov'),
        ('Celene Edinboro', 'cedinboroi@ehow.com'),
         ('Aeriell McCartney', 'amccartneyj@nsw.gov.au');

insert into applicant (name, lastname, jobPosition, level_of_expertise, email) values
 ('Doralin', 'Pilsbury', 'Subaru', '1', 'dpilsbury0@fda.gov'),
 ('Rennie', 'Imort', 'Kia', '2', 'rimort1@mtv.com'),
 ('Hodge', 'Bellay', 'Chevrolet', '2', 'hbellay2@twitter.com'),
 ('Emily', 'Lewens', 'Chevrolet', '0', 'elewens3@twitter.com'),
 ('Mariska', 'Gowdridge', 'Aston Martin', '0', 'mgowdridge4@imdb.com'),
 ('Vin', 'Buxcy', 'BMW', '1', 'vbuxcy0@addthis.com'),
 ('Reyna', 'Normand', 'Pontiac', '1', 'rnormand1@list-manage.com'),
 ('Engracia', 'Whipp', 'Infiniti', '4', 'ewhipp2@sun.com'),
 ('Wileen', 'MacLice', 'Pontiac', '0', 'wmaclice3@guardian.co.uk'),
 ('Verena', 'Keefe', 'Dodge', '1', 'vkeefe4@people.com.cn'),
 ('Blythe', 'Lemoir', 'Dodge', '1', 'blemoira@gmpg.org'),
 ('Idalina', 'Grichukhin', 'GMC', '4', 'igrichukhinb@netvibes.com'),
 ('Colet', 'Prise', 'Buick', '0', 'cprisec@columbia.edu'),
 ('Xena', 'Prene', 'Pontiac', '4', 'xprened@ehow.com'),
 ('Carmen', 'McAlarney', 'Porsche', '4', 'cmcalarneye@washingtonpost.com'),
 ('Blanch', 'Mockford', 'Mitsubishi', '4', 'bmockfordf@nba.com'),
 ('Galvan', 'Breznovic', 'Ford', '0', 'gbreznovicg@nih.gov'),
 ('Allyn', 'McDuall', 'Chrysler', '2', 'amcduallh@apache.org'),
 ('Merridie', 'Danniel', 'Volkswagen', '4', 'mdannieli@ox.ac.uk'),
 ('Willdon', 'Baile', 'Mercury', '0', 'wbailej@desdev.cn'),
 ('Consalve', 'Hake', 'Chevrolet', '1', 'chakek@google.com.au'),
 ('Kerwinn', 'Caley', 'Mercury', '2', 'kcaleyl@liveinternet.ru'),
 ('Shay', 'Arpe', 'Chevrolet', '2', 'sarpem@wired.com'),
 ('Carleton', 'Wythill', 'Ford', '1', 'cwythilln@usgs.gov'),
 ('Debbi', 'Arnao', 'Acura', '0', 'darnaoo@dion.ne.jp'),
 ('Dahlia', 'Bircher', 'Buick', '0', 'dbircherp@uol.com.br'),
 ('Melinde', 'Jeanequin', 'Buick', '0', 'mjeanequinq@merriam-webster.com'),
 ('Brunhilde', 'Bointon', 'Jeep', '1', 'bbointonr@spiegel.de'),
 ('Delbert', 'MacGillicuddy', 'Mercury', '0', 'dmacgillicuddys@mac.com'),
 ('Donal', 'Vamplers', 'Infiniti', '0', 'dvamplerst@jimdo.com'),
 ('Alana', 'Steenson', 'GMC', '1', 'asteensonu@xing.com'),
 ('Grissel', 'Dormon', 'Pontiac', '4', 'gdormonv@bbb.org'),
 ('Hoyt', 'Schooling', 'Audi', '1', 'hschoolingw@nationalgeographic.com'),
 ('Archie', 'Munkton', 'Audi', '3', 'amunktonx@mapy.cz'),
 ('Nata', 'Firby', 'Pontiac', '4', 'nfirbyy@fema.gov'),
 ('Silvana', 'Snipe', 'BMW', '3', 'ssnipez@scribd.com'),
 ('Reggi', 'Downton', 'Porsche', '1', 'rdownton10@samsung.com'),
 ('Gerry', 'Chadwyck', 'Toyota', '0', 'gchadwyck11@bizjournals.com'),
 ('Ellswerth', 'Kinnane', 'Jaguar', '1', 'ekinnane12@opera.com'),
 ('Arlyne', 'Cohalan', 'Scion', '0', 'acohalan13@nih.gov'),
 ('Debra', 'Pettendrich', 'Chevrolet', '1', 'dpettendrich14@cbslocal.com'),
 ('Obadias', 'Fegan', 'Mercury', '2', 'ofegan10@yahoo.com'),
 ('Marchelle', 'Curnnok', 'Hyundai', '2', 'mcurnnok11@jugem.jp'),
 ('Ansel', 'Morilla', 'BMW', '1', 'amorilla12@cdc.gov'),
 ('Hercules', 'Yegorev', 'Volkswagen', '3', 'hyegorev13@paypal.com'),
 ('Emelita', 'Hyrons', 'GMC', '0', 'ehyrons14@google.com'),
 ('Abe', 'Natwick', 'Toyota', '4', 'anatwick1a@surveymonkey.com'),
 ('Mariya', 'MacWilliam', 'Chevrolet', '1', 'mmacwilliam1b@networksolutions.com'),
 ('Lona', 'Varty', 'Buick', '3', 'lvarty1c@naver.com'),
 ('Kalina', 'Nobes', 'Volvo', '0', 'knobes1d@istockphoto.com'),
 ('Jesselyn', 'Boner', 'Scion', '0', 'jboner1e@ihg.com'),
 ('Serena', 'Korneichuk', 'Honda', '3', 'skorneichuk1f@devhub.com'),
 ('Ewell', 'Salvidge', 'Mercury', '0', 'esalvidge1g@princeton.edu'),
 ('Kurtis', 'Bidmead', 'Chrysler', '2', 'kbidmead1h@webs.com'),
 ('Zelda', 'Howett', 'Ford', '1', 'zhowett1i@businesswire.com'),
 ('Bamby', 'Curd', 'Acura', '3', 'bcurd1j@mediafire.com'),
 ('Andriette', 'Cowoppe', 'Chevrolet', '0', 'acowoppe1k@yandex.ru'),
 ('Norina', 'Bichener', 'Toyota', '4', 'nbichener1l@is.gd'),
 ('Marion', 'Chicken', 'Ford', '3', 'mchicken1m@cmu.edu'),
 ('Sayers', 'Marham', 'Honda', '3', 'smarham1n@wix.com'),
 ('Oriana', 'Kearley', 'BMW', '1', 'okearley1o@angelfire.com'),
 ('Moises', 'Warbrick', 'Volkswagen', '1', 'mwarbrick1p@sohu.com'),
 ('Demetrius', 'Borland', 'Mitsubishi', '3', 'dborland1q@independent.co.uk'),
 ('Norry', 'Moffet', 'Honda', '0', 'nmoffet1r@ehow.com'),
 ('Rivkah', 'Dunstall', 'Nissan', '1', 'rdunstall1s@google.cn'),
 ('Jorrie', 'Malacrida', 'Ford', '0', 'jmalacrida1t@simplemachines.org'),
 ('Zebulen', 'Sherlaw', 'Nissan', '2', 'zsherlaw1u@guardian.co.uk'),
 ('Terri-jo', 'Ballay', 'Chevrolet', '3', 'tballay1v@reverbnation.com'),
 ('Dag', 'Maudling', 'Lexus', '3', 'dmaudling1w@uiuc.edu'),
 ('Yardley', 'Labrum', 'Land Rover', '1', 'ylabrum1x@xinhuanet.com'),
 ('Melisse', 'Scallon', 'Pontiac', '1', 'mscallon1y@sciencedaily.com'),
 ('Cello', 'Crasswell', 'Cadillac', '4', 'ccrasswell1z@bandcamp.com'),
 ('Kellen', 'Kybird', 'Mazda', '4', 'kkybird20@mit.edu'),
 ('Elijah', 'Muckersie', 'Ford', '1', 'emuckersie21@parallels.com'),
 ('Loren', 'Brehat', 'Volkswagen', '4', 'lbrehat22@113.com'),
 ('Melvin', 'O''Donegan', 'Lexus', '1', 'modonegan23@cnn.com'),
 ('Ciro', 'Toulamain', 'Chevrolet', '1', 'ctoulamain24@abc.net.au'),
 ('Andrey', 'Sivills', 'Chrysler', '1', 'asivills20@nps.gov'),
 ('Dasha', 'Felipe', 'Cadillac', '0', 'dfelipe21@youtu.be'),
 ('Dorella', 'Roswarn', 'Dodge', '2', 'droswarn22@dedecms.com'),
 ('Norrie', 'Heliot', 'Audi', '2', 'nheliot23@creativecommons.org'),
 ('Johnath', 'Perkinson', 'Audi', '3', 'jperkinson24@netvibes.com'),
 ('Audrey', 'Yetts', 'Saab', '2', 'ayetts2a@example.com'),
 ('Philipa', 'Moreton', 'Chrysler', '4', 'pmoreton2b@wikimedia.org'),
 ('Rae', 'Physick', 'Lincoln', '2', 'rphysick2c@prnewswire.com'),
 ('Danice', 'Lavender', 'Chevrolet', '4', 'dlavender2d@mediafire.com'),
 ('Nikki', 'Male', 'Chevrolet', '4', 'nmale2e@nationalgeographic.com'),
 ('Johnette', 'Snazel', 'BMW', '1', 'jsnazel2f@youtu.be'),
 ('Amil', 'Duigan', 'Jeep', '3', 'aduigan2g@lycos.com'),
 ('Spenser', 'Gai', 'Ford', '2', 'sgai2h@spotify.com'),
 ('Colly', 'Haines', 'Acura', '4', 'chaines2i@artisteer.com'),
 ('Elmore', 'Gowers', 'Nissan', '2', 'egowers2j@house.gov'),
 ('Damien', 'Billiard', 'Ford', '4', 'dbilliard2k@about.me'),
 ('Boyd', 'Arnatt', 'Mazda', '2', 'barnatt2l@google.ca'),
 ('Sally', 'Noden', 'Honda', '0', 'snoden2m@ebay.co.uk'),
 ('Ellette', 'Tull', 'Mitsubishi', '4', 'etull2n@soup.io'),
 ('Kaycee', 'Lampens', 'Nissan', '0', 'klampens2o@friendfeed.com'),
 ('Daryle', 'Chamley', 'Mercury', '3', 'dchamley2p@liveinternet.ru'),
 ('Staci', 'Storms', 'Mercury', '4', 'sstorms2q@un.org'),
 ('Alfreda', 'Normansell', 'Toyota', '0', 'anormansell2r@oaic.gov.au');